---
title: "Cox PH"
output: pdf_document
date: "2025-09-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Fine Grey 1
## Clean Data
```{r}
data <- read.csv("/gpfs/gibbs/project/jain_snigdha/shared/EM_PTOT_project/ot_pt_statistical_analysis/block_with_categorical_clustered.csv", na.strings = c("", "NA", "N/A"))

keep_cols <- c("age", "sex_category", "race_category", "ethnicity_category", 
               "language", "insurance", "bmi", "charlson_comorbidity_index", 
               "ICU_type", "mean_heart_rate_0_24h", "mean_map_0_24h", 
               "mean_fio2_0_24h", "mean_peep_0_24h", "sofa_total",  "coma_0_24h", 
               "pressor_24h", "paralytics_24h", "yellow_ever", 
               "delayed_yellow_PT_zeroed", "yellow_to_discharge_hours")

df <- data[ , keep_cols]
df <- df[df$yellow_ever == "True", ]

pt_time <- df$delayed_yellow_PT_zeroed 
disc_time <- df$yellow_to_discharge_hours 

# Time to first of PT or competing (discharge)
df$first_time <- pmin(pt_time, disc_time, na.rm = TRUE)
# Truncate follow-up at 72h for everyone
df$time_72 <- pmin(df$first_time, 72, na.rm = TRUE)
df$time_72 <- pmax(df$time_72, 0)  # handle negative discharg time: discharge before yellow eligible

## Apply the 72h window 
# status = 0 -> censored at min(72h, last known time) if neither of below happened by 72h
# status = 1 -> event of interest (PT order) within 72h
# status = 2 -> competing event occurs before PT, within 72h

df$status_fg <- integer(nrow(df))
# Event of interest: PT within 72h
df$status_fg[!is.na(pt_time) & pt_time <= 72] <- 1
# Competing event: discharge occurs first (and within 72h)
competing <- (!is.na(disc_time)) & (is.na(pt_time) | disc_time < pt_time) & (disc_time <= 72)
df$status_fg[competing] <- 2

sum(df$status_fg==0)
sum(df$status_fg==1)
sum(df$status_fg==2)

cols <- c("age", "sex_category", "race_category", "ethnicity_category", "language", 
          "insurance", "bmi", "charlson_comorbidity_index", "ICU_type", 
          "mean_heart_rate_0_24h", "mean_map_0_24h", "mean_fio2_0_24h", 
          "mean_peep_0_24h", "sofa_total", "coma_0_24h", "pressor_24h", 
          "paralytics_24h")

mask <- complete.cases(df[, cols]) & complete.cases(df[, c("time_72","status_fg")])
df_fit <- df[mask, ]

cat_vars <- c("sex_category","race_category","ethnicity_category","language",
              "insurance","ICU_type")
df_fit[cat_vars] <- lapply(df_fit[cat_vars], as.factor)
```

## Fit model
```{r}
library(prodlim) 
library(riskRegression) 

form_fg1 <- as.formula(paste("Hist(time_72, status_fg, cens.code = 0) ~", 
                             paste(cols, collapse = " + ")))

fit_fg1 <- FGR(formula = form_fg1, data = df_fit, cause = 1)
summary(fit_fg1)
```

# Fine Grey 2
```{r}
data <- read.csv("/gpfs/gibbs/project/jain_snigdha/shared/EM_PTOT_project/ot_pt_statistical_analysis/block_with_categorical_clustered.csv", na.strings = c("", "NA", "N/A"))

keep_cols <- c("age", "sex_category", "race_category", "ethnicity_category", 
               "language", "insurance", "bmi", "charlson_comorbidity_index", 
               "ICU_type", "mean_heart_rate_0_24h", "mean_map_0_24h", 
               "mean_fio2_0_24h", "mean_peep_0_24h", "sofa_total",  "coma_0_24h", 
               "pressor_24h", "paralytics_24h", "imv_to_discharge_hours", 
               "is_dead_hosp", "pt_pre24_or_post48_Yellow")

df <- data[ , keep_cols]
df <- df[df$is_dead_hosp == "False", ]
df$status[pt_pre24_or_post48_Yellow == 1] <- 1


```








